added new conditions

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -13,6 +13,17 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Verify Folder Exists
+        run: echo "Folder name: '${{ github.event.inputs.folder }}'"
+
+      - name: Verify Folder Exists
+        if: env.skip_build == 'false'
+        run: |
+          if [ ! -d "${{ github.event.inputs.folder }}" ]; then
+            echo "Error: Folder '${{ github.event.inputs.folder }}' does not exist."
+            exit 1
+          fi
+
       - name: Check for Folder Input
         id: check-folder
         run: |
